language: android
jdk: oraclejdk8
sudo : required

env:
  global:
    - MALLOC_ARENA_MAX=2

android:
  components:
    - tools
    - platform-tools
    - tools
    - android-26
    - build-tools-26.0.2
    - extra-android-m2repository
    - extra-google-m2repository

script:
  - ./gradlew build check jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
